- hosts: allserver
  vars:
     images: idndevops/web-custo:v1.0m
  tasks:
     - name: install docker-py di ubuntu
       apt:
         name: "{{ item }}"
         state: present 
       loop:
          - python3
          - python3-docker
       when: ansible_facts['os_family'] == "Debian"

     - name: install docker-py di centos
       yum:
          name: "{{ item }}"
          state: present
       loop:
          - epel-release
          - python3
          - python3-docker
       when: ansible_facts[ 'os_family' ] == "Redhat"

     - name: running container
       docker_container:
          name: docker-ansible
          image: "{{ image }}"
          published_ports:
             - 10000:80
          recreate: yes
          state: started
          restart_policy: always
          pull: yes  
